name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - numpy
  - scipy
  - plotly
  - pygam
  - pymc
  - scikit-learn
  - statsmodels
  - keras
  - bs4
  - matplotlib
  - seaborn
